name: reimburstment-calc
version: '3.9'

services:
  db:
    container_name: db
    image: 'postgres:16'
    restart: always
    environment:
      - POSTGRES_DB=calc
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - db-network
    ports:
      - '6500:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  db-network:
    driver: bridge

volumes:
  pgdata: 
    driver: local

