name: Fly Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Create a tunnel to the database
        run: flyctl proxy 5433:5432 -a re-calc-postgres &
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_AUTH_TOKEN }}
      - name: Build integration tests
        run: |
          docker-compose -f "docker-compose.integration.yml" up --build \
            --build-arg PROD_DB=${{ secrets.PROD_DB_TUNNEL }}
      - name: Run integration tests
        run: |
          docker-compose -f "docker-compose.integration.yml" up \
            --abort-on-container-exit \
            --exit-code-from frontend
      - name: Build deployment images
        run: |
          flyctl deploy --build-only --build-arg "PROD_DB=${{ secrets.PROD_DB_TUNNEL }}" ./axum-backend
          flyctl deploy --build-only ./svelte-frontend
      - name: Deploying the app
        run: |
          flyctl deploy --build-arg "PROD_DB=${{ secrets.PROD_DB_TUNNEL }}" ./axum-backend --env "PORT=8080"
          flyctl deploy ./svelte-frontend


