name: Unit Tests
on:  
  pull_request:
    branches:
      - master

jobs:
  deploy:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run unit tests
        run: docker-compose -f docker-compose.test.yml up --build
